### ISSUE TITLE
Picasanew - ver 2 (use OAuth 2.0)

### ISSUE THREAD

**Issue by phuclh** [ptcong/php-remote-image-uploader#10]
I see you just updated your plugin to ver 2, thank you for that. But I have 2 questions:

1. Do I still keep on uploading by ver 1 like:

```php
$uploader = ChipVN_ImageUploader_Manager::make('Picasa');
$uploader->login('your account', 'your password');
// you can set upload to an albumId by array of albums or an album, system will get a random album to upload
//$uploader->setAlbumId(array('51652569125195125', '515124156195725'));
//$uploader->setAlbumId('51652569125195125');
echo $uploader->upload(getcwd(). '/test.jpg');
// this plugin does not support transload image
```

2. In your demo code:
```php
if (!$uploader->hasValidToken()) {
    $uploader->getOAuthToken('http://yourdomain.com/test.php');
}
```

I don't understand the link's mean (`http://yourdomain.com/test.php`) and its operation?

Thank you.

**Comment by ptcong** [comment]
It's uri callback, after you authorized, google will redirect you back to the uri with parameter `code=....`, then the library will exchange the code with google to get token.

**Comment by Drezzler** [comment]
But , what should test.php contain ?

**Comment by ptcong** [comment]
Google just stopped supporting API v1, so you should use v2 for uploading.
You can see the code i have written in README, also need an Oauth API ID, secret.
Go to console.developers.google.com and create an API for your script.
