### ISSUE TITLE
Fatal error: Call to undefined method ChipVN_Cache_Adapter_Session::deleteGroup() in /home/**********/public_html/admin/classes/ChipVN/ImageUploader/Plugins/Picasa.php on line 56

### ISSUE THREAD

**Issue by trname** [ptcong/php-remote-image-uploader#11]
I get an error like this
Fatal error: Call to undefined method ChipVN_Cache_Adapter_Session::deleteGroup() in /home/**********/public_html/admin/classes/ChipVN/ImageUploader/Plugins/Picasa.php on line 56

source code;
include 'classes/ChipVN/ClassLoader/Loader.php';
ChipVN_ClassLoader_Loader::registerAutoLoad();
$uploader = ChipVN_ImageUploader_Manager::make('Picasa');
$uploader->login('*********', '*********');
$uploader->setAlbumId('*************');
echo $uploader->upload($file_path);

**Comment by ptcong** [comment]
You should read the README file carefully. This library dependencies to some libraries. You must download all of them for running the library.
