### ISSUE TITLE
This code not work, seem only for advertisment to earn money

### ISSUE THREAD

**Issue by dungla2011** [ptcong/php-remote-image-uploader#12]
Lost time to check this
Bye forever!

**Comment by trandaihung** [comment]
This is not a place for troll.

**Comment by ptcong** [comment]
@trandaihung are you dungla2011 ?
This project got 30 star, and it is not a troll, lol

@dungla2011 read USAGE to how to use this

**Comment by trandaihung** [comment]
@ptcong Sorry? But I said he was trolling, not the project.

**Comment by ductho1201** [comment]
I got a problem when trying upload to imgur use client_id and client_secret ( i got from imgur when create new application ) but the image not avaiable on my album. I don't know my mistake or incorrect understanding some information? Please help me. Tks you first.
