### ISSUE TITLE
Imgur plugin does not upload to declared account

### ISSUE THREAD

**Issue by ductho1201** [ptcong/php-remote-image-uploader#13]
I got a problem when trying upload to imgur use client_id and client_secret ( i got from imgur when create new application ) but the image not avaiable on my album. I don't know my mistake or incorrect understanding some information? Please help me. Tks you first.

**Comment by ptcong** [comment]
What's problem you got ?
an error message or just not upload to your account ?

**Comment by ductho1201** [comment]
It upload successfully but not to my account. When i check in my imgur image page, there is no picture here. And one more, your new Http/Client.php library got a conflict with Abtract.php file in plugin.

**Comment by ptcong** [comment]
Ya, if you use composer, you will not see any conflicts because it dependen on Http Client 2.x (old version).

I will check this issue when i have time. If you're free, please make a PR for this issue.

**Comment by ductho1201** [comment]
Ok, i will try use Composer.

**Comment by ptcong** [comment]
@ductho1201 I have released 6.x version, please check.
