### ISSUE TITLE
Can not create a new album for storage every 2000 photos Picasa

### ISSUE THREAD

**Issue by hd00842** [ptcong/php-remote-image-uploader#15]
I've used it works pretty well, but it does not automatically create an album in 2000 when the album containing photos

**Comment by ptcong** [comment]
Seems not right, it had have some lines of code to check when an album remaning is 0, it will automatic create a new album.
https://github.com/ptcong/php-remote-image-uploader/blob/6.x/src/RemoteImageUploader/Adapters/Picasa.php#L297.
Try to delete your cache folder and try again

**Comment by hd00842** [comment]
I do not understand why it does not work with my application

**Comment by ptcong** [comment]
Try this https://github.com/ptcong/php-remote-image-uploader/releases/tag/6.0.3
I've added some code to cover this issue.

**Comment by algobasket** [comment]
My upload code runs on local server but cannot getting error 500 when i upload the same code to my online server . Please help me asap . Thanks
