### ISSUE TITLE
spaces in title and description

### ISSUE THREAD

**Issue by saturnino** [ptcong/php-remote-image-uploader#16]
I've made some changes in the flickr adapter in order to post title, description and tagsduring upload

like this  
`protected function doUpload($file, $title = '', $description = '', $tags = '')
    {
        $params = $this->getParameters(array(
			'title'			 => $title,
            'description'    => $description,
            'tags'           => $tags,
            'is_public'      => 1,
            'is_friend'      => '',
            'is_family'      => '',
            'content_type'   => 1, // 1: photo, 2:screenshot
            'safety_level'   => '',
            'hidden'         => '',
            'oauth_token'    => $this->getAccessToken(),
        ));
		

        list($url, $params) = $this->prepareRequestData(self::UPLOAD_ENDPOINT, 'POST', $params);
		
		//return $params;

        $request = $this->createRequest(self::UPLOAD_ENDPOINT, 'POST')
            ->withFormParam($params)
            ->withFormFile('photo', $file)
            ->send();

        if (!$photoId = Helper::match('#<photoid>(\w+)</photoid>#', $request)) {
            parse_str($request, $result);

            if (isset($result['oauth_problem'])) {
                throw new Exception(sprintf('Upload failed: "%s"', $result['oauth_problem']));
            } else {
                $error = Helper::match('#code="(.+?)"#', $request);
                $msg = Helper::match('#msg="(.+?)"#', $request);
                throw new Exception(sprintf('Upload failed: "%s" (%d)', $msg, $error));
            }
        }
        $result = $this->callApi('flickr.photos.getInfo', array(
            'photo_id' => $photoId,
        ));
		
		return array(	'url' => $this->getPhotoUrl($result['photo']),
			 			'photo_id' => $this->getPhotoId($result['photo'])
						);						
        
		return $this->getPhotoUrl($result['photo']);
    }`

but if ther is spaces in title or in description i've got a signature error

`<br />
<b>Fatal error</b>:  Uncaught exception 'Exception' with message 'Upload failed: &quot;signature_invalid&quot;' in /var/www/clients/client0/web7/web/tests/invinoveritas/lib/ptcong/vendor/ptcong/php-image-uploader/src/RemoteImageUploader/Adapters/Flickr.php:169
Stack trace:
#0 /var/www/clients/client0/web7/web/tests/invinoveritas/lib/ptcong/vendor/ptcong/php-image-uploader/src/RemoteImageUploader/Factory.php(220): RemoteImageUploader\Adapters\Flickr-&gt;doUpload('/var/www/client...', 'dgdfg dg g', ' dgf dg', 'Bourgogne')
#1 /var/www/clients/client0/web7/web/tests/invinoveritas/save-my-image.php(38): RemoteImageUploader\Factory-&gt;upload('/var/www/client...', 'dgdfg dg g', ' dgf dg', 'Bourgogne')
#2 {main}
  thrown in <b>/var/www/clients/client0/web7/web/tests/invinoveritas/lib/ptcong/vendor/ptcong/php-image-uploader/src/RemoteImageUploader/Adapters/Flickr.php</b> on line <b>169</b><br />
`

I've tried several encoding method without success. 

Could you help me about this problem please?
thank you

**Comment by ptcong** [comment]
i also faced with this issue before but without success, lol.
It seems caused by Flickr sugnature generate in their server.

**Comment by Maef** [comment]
Maybe this helps? http://whatwebwhat.com/en/page/350/oauth-and-url-encoding

**Comment by ptcong** [comment]
Could you guys check that oauth_urlencode function and make a PR for Flickr plugin if it works ?

**Comment by Maef** [comment]
Just created a PR

**Comment by ptcong** [comment]
Thanks
