### ISSUE TITLE
Change flickr api mới không upload được

### ISSUE THREAD

**Issue by veerkun** [ptcong/php-remote-image-uploader#18]
Mình dùng để upload flickr, mình change api key và serect thì nó báo 

> Uncaught exception 'Exception' with message 'Transload failed. Upload failed: "Invalid auth token"

Hình như nó còn lưu temp token thì phải

**Comment by ptcong** [comment]
Bạn phải oauth lại để có token theo api của bạn.

**Comment by veerkun** [comment]
Oauth lại bằng cách nào vậy

**Comment by veerkun** [comment]
Mình đã làm được.
thank a
