### ISSUE TITLE
max file size

### ISSUE THREAD

**Issue by bowodesign** [ptcong/php-remote-image-uploader#19]
Hi @ptcong ,

Just curious what is the max size to upload on picasa, because i try to upload image like this one

http://plusquotes.com/images/quotes-img/santa_claus_PNG9972.png - size about 1mb 
or this  one 
http://mr2.phpwerx.net/Photos/Sully/NYC/Yankee/Panoramas/full/yankee4.jpg - size about 8mb 

its failed, the error log is like this

```
PHP Fatal error:  Uncaught exception 'Exception' with message 'Transload failed' in /Applications/MAMP/htdocs/picasa/vendor/ptcong/php-image-uploader/src/RemoteImageUploader/Adapters/Picasa.php:236
Stack trace:
#0 /Applications/MAMP/htdocs/picasa/vendor/ptcong/php-image-uploader/src/RemoteImageUploader/Factory.php(247): RemoteImageUploader\Adapters\Picasa->doTransload('http://plusquot...')
#1 /Applications/MAMP/htdocs/picasa/untitled.php(26): RemoteImageUploader\Factory->transload('http://plusquot...')
#2 {main}
  thrown in /Applications/MAMP/htdocs/picasa/vendor/ptcong/php-image-uploader/src/RemoteImageUploader/Adapters/Picasa.php on line 236
```
is there any way to set the max size file

thank you :)

**Comment by ptcong** [comment]
There is no size limit here, the problem may caused by connection between your server to that links or your server to hosting service.
You should dig to the code and check what's real message. Transload failed just a general message.

**Comment by bowodesign** [comment]
You right, I think its because the connection, I try this on localhost before, and when I try to upload its work perfect!

Thx for this amazing code @ptcong  :)
