### ISSUE TITLE
Hello, how to refresh OAuthToken by server backgrounp's service?

### ISSUE THREAD

**Issue by yamol700304** [ptcong/php-remote-image-uploader#9]
Your source code is so good, I can upload file to picasa now,

but the OAuthToken is expire so soon,

I need refresh OAuthToken by server backgrounp's service,

can you give me your source code?  I can pay for it  ~ thank you!

**Comment by ptcong** [comment]
See, Picasanew (as i called) have  `refreshToken(array $token)` method to refresh token. You can use it for refreshing token in background.

**Comment by ptcong** [comment]
is it ok now ?

**Comment by yamol700304** [comment]
Yes, it's ok , thank you so mush!
